### ISSUE TITLE
[Firefox] Error. Selection.getRangeAt: 0 is out of range.

### ISSUE THREAD

**Issue by MarkRH** [erosman/support#482]
I happen to be using Firefox 100.0.1 and version 1.9 of the extension.  The are some places where when I use the side-bar or context-menu to apply a BBC Code or HTML style to something I've highlighted I'll get this error dialog.

![image](https://i.imgur.com/AzorKkP.png)

It does apply the changes to the text so that part still works.  I just get this dialog on the bottom-right.  One place this happens at is https://www.dslreports.com/forum/mozilla .

Other places I don't get error dialog. 

Thanks,
Mark H.

**Comment by erosman** [comment]
Thank you for the report. The mentioned URL requires login to test. I will try to find out the reason.

**Comment by MarkRH** [comment]
Thanks for looking at it.  I'm trying to find something else that you don't need an account for.

**Comment by MarkRH** [comment]
Thought I would mention that it also happens on Reddit.  Note: I am still using the old style Reddit. My option to use the new Reddit is still unchecked.

**Comment by erosman** [comment]
I am not registered at Reddit either.

**Comment by erosman** [comment]
I found out the reason. I was trying it on google translate page and it happened. It happens when they are more than one frames (i.e. `iframe`) and the error comes from the other iframes.

I will see how I can eliminate the notice.

_PS. I am traveling now and not at my usual location._

**Comment by MarkRH** [comment]
Ahhh.. well, you being able to duplicate it is the first step.  Have fun with your travels. :)

**Comment by Korb** [comment]
I also get this message probably every time I use Edit

> There was an error with the operation
> Error: Selection.getRangeAt: 0 is out of range

![2024-05-29_17-07-34 copy](https://github.com/erosman/support/assets/3509797/07171266-a849-4db4-acd3-731e553bbcdb)

I don't use the sidebar, but only the context menu and keyboard.

Mozilla Firefox 127.0b7 (64-bit)
Edit 1.9 (January 17, 2023)
Microsoft Windows 10.0.19045.4412

**Comment by erosman** [comment]
Which pages are you trying it on?
Some pages wont allow the operation due to the CSP (Content Security Policy).

However, above issue with CSP should be fixed in Firefox 128.
ref: [CSP 'sandbox' directive prevents content scripts from matching, due to unique origin, breaking also browser features](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641)

**Comment by Korb** [comment]
> Which pages are you trying it on?

In this case - CS-Cart CMS. Also, I can reproduce this error on the sites keep.google.com, calendar.google.com, messages.google.com, mail.google.com, mail.proton.me...

On Github, when performing the same actions, the error message does not appear.

**Comment by Korb** [comment]
On reddit.com, the same error appears simultaneously with the loss of functionality of the extension in the reply input field in the topic in `Markdown Editor` mode. That is, for example, when selecting text and choosing `Edit` / `Markdown` / `URL` in the context menu, nothing happens, except for the error message.

Mozilla Firefox 133.0b7 (64-bit)
Edit 1.9 (Oct 5, **2021**)
Microsoft Windows 10.0.19045.5073

**Comment by erosman** [comment]
Some pages generate special content like docs in Google or calender, spreadsheet etc. These are not part of the parent webpage and thus may no be accessible to the extension.

They would need to be properly checked. 

On reddit, the reply box is crated using [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) and I suspect the extension doesn't inject into the shadow DOM. It needs further investigation.

**Comment by Wizardgoat** [comment]
I'm using Edit for the first time today, on Firefox 136 (64-bit). I've tested it in text boxes on GoComics/Luann - http://www.gocomics.com/luann - which does not require a paid account (you can sign up for free).

The HTML is successfully inserted/removed on each attempt, but I still get this message. It's a nuissance, because I have to clear all these messages out of Windows 10 notifications.
